FROM golang:1.8@sha256:f0b5dab7581eddb49dabd1d1b9aa505ca3edcdf79a66395b5bfa4f3c036b49ef

WORKDIR /go/src/app
VOLUME /go/src/app
ENV CGO_ENABLED=0
RUN go get github.com/tockins/realize
CMD ["/go/bin/realize", "run"] 

# Mount your project as /go/src/app, for example:
# docker run --rm -it -v ~/go/src/github.com/lizrice/hello-container-world/Example1:/go/src/app lizrice/hello-realize 